- include: centos.yml
  when: ansible_distribution == "CentOS"

- include: debian.yml
  when: ansible_distribution == "Debian"

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

#####################
# Common
- name: "Ensure the collectd exec module directory exists"
  file: >
    path=/opt/collectd-exec-modules
    state=directory
  tags:
    - collectd
    - pkgs
    - libs

- name: "Make sure {{ collectd_d_config_dir }} is present"
  file: >
    path={{ collectd_d_config_dir }}
    state=directory
  tags:
    - collectd
    - files
    - configs

- name: "Make sure /usr/lib/collectd/scripts is present"
  file: >
    path=/usr/lib/collectd/scripts
    state=directory
  tags:
    - collectd
    - local_scripts
    - files
    - configs

- name: "Upload plugin configs"
  template: >
    src=plugin-configs/{{ item }}.conf.j2
    dest={{ collectd_d_config_dir }}/{{ item }}.conf
    mode=0644
  with_items: collectd_plugins
  notify:
    - Restart collectd
  tags:
    - collectd
    - files
    - configs

- name: "Generate auth-file"
  template: >
    src=auth.file.j2
    dest={{ collectd_authfile }}
    mode=0600
  when: collectd_network_pass is defined
  notify:
    - Restart collectd
  tags:
    - collectd
    - files
    - configs

- name: "Upload local-configs"
  template: >
    src={{ item }}
    dest={{ collectd_d_config_dir }}/{{( item |basename| splitext )[0]}}
    mode=0644
  with_fileglob: files/collectd/{{ ansible_hostname }}/*.j2
  notify:
    - Restart collectd
  tags:
    - collectd
    - local_configs
    - files
    - configs

- name: "Upload extra scripts"
  copy: >
    src={{ item }}
    dest=/usr/lib/collectd/scripts/
    group=nogroup
    mode=0664
  with_fileglob: files/collectd/scripts/*
  tags:
    - collectd
    - local_scripts
    - files
    - configs

- name: "Install coretemp plugin for collectd"
  copy: >
    src=collectd-coretemp.sh
    dest=/opt/collectd-exec-modules/
    mode=0755
    owner=root
    group=root
  notify:
    - Restart collectd
  tags:
    - collectd
    - files

- name: "Install /etc/collectd.conf"
  template: >
    src=collectd.conf.j2
    dest={{ collectd_config_dest }}
    mode=0644
  notify:
    - Restart collectd
  tags:
    - collectd
    - files
    - configs

- name: "Add the coretemp kernel module"
  modprobe: >
    name=coretemp
    state=present
  when: monitor_coretemp
  tags:
    - collectd
    - files
    - configs

- name: "Make sure collectd is running"
  service: >
    name=collectd
    state=running
    enabled=yes
    runlevel=5
  tags:
    - collectd
